export const mockBranches = [
  {
    id: 1,
    slug: "ramallah",
    nameAr: "رام الله",
    nameEn: "Ramallah",
    phone: "0599123456",
    whatsApp: "+970599123456",
    bannerImagePath: null,
    discountPercent: 10,
    isActive: true,
    sortOrder: 1,
    latitude: 31.902,
    longitude: 35.203,
    openingTime: "09:00",
    closingTime: "23:00",
    deliveryFee: 10,
    deliveryZones: [
      { name: "داخل رام الله", fee: 10 },
      { name: "ضواحي رام الله", fee: 20 },
      { name: "المنطقة الصناعية", fee: 15 }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    slug: "alBireh",
    nameAr: "البيرة",
    nameEn: "Al Bireh",
    phone: "0599123457",
    whatsApp: "+970599123457",
    bannerImagePath: null,
    discountPercent: 0,
    isActive: true,
    sortOrder: 2,
    latitude: 31.912,
    longitude: 35.213,
    openingTime: "10:00",
    closingTime: "02:00",
    deliveryFee: 15,
    deliveryZones: [
      { name: "داخل البيرة", fee: 10 },
      { name: "محيط البيرة", fee: 15 }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const mockCategories = [
  { id: 101, nameAr: "برجر لحم", nameEn: "Beef Burgers", branchId: null, sortOrder: 1, iconClass: "🍔", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 4 },
  { id: 102, nameAr: "برجر دجاج", nameEn: "Chicken Burgers", branchId: null, sortOrder: 2, iconClass: "🍗", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 2 },
  { id: 103, nameAr: "ساندويتشات", nameEn: "Sandwiches", branchId: null, sortOrder: 3, iconClass: "🥪", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 2 },
  { id: 104, nameAr: "وجبات عائلية وبوكسات", nameEn: "Family Meals & Boxes", branchId: null, sortOrder: 4, iconClass: "🍱", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 1 },
  { id: 105, nameAr: "مقبلات", nameEn: "Appetizers", branchId: null, sortOrder: 5, iconClass: "🍟", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 3 },
  { id: 106, nameAr: "مشروبات باردة", nameEn: "Cold Drinks", branchId: null, sortOrder: 6, iconClass: "🥤", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 3 },
  { id: 107, nameAr: "حلويات", nameEn: "Desserts", branchId: null, sortOrder: 8, iconClass: "🍰", isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), productCount: 2 }
];

export const mockProducts = [
  {
    id: 1001,
    nameAr: "أبتاون برجر",
    nameEn: "Uptown Burger",
    descriptionAr: "شريحة لحم دبل، بصل مكرمل، خس، طماطم، جبنة شيدر، وصوص أبتاون",
    descriptionEn: "Double beef patty, caramelized onions, lettuce, tomato, cheddar cheese, and Uptown sauce",
    basePrice: 35,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1002,
    nameAr: "ترافل برجر",
    nameEn: "Truffle Burger",
    descriptionAr: "شريحة لحم بصوص الترافل الفاخر، مشروم، جبنة سويسرية",
    descriptionEn: "Beef patty with premium truffle sauce, mushrooms, and Swiss cheese",
    basePrice: 37,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1003,
    nameAr: "سموك هاوس برجر",
    nameEn: "Smokehouse Burger",
    descriptionAr: "شريحة لحم، بيكون بقري، حلقات بصل مقلية، صوص الباربكيو المدخن",
    descriptionEn: "Beef patty, beef bacon, fried onion rings, smoked BBQ sauce",
    basePrice: 33,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 3,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1004,
    nameAr: "كلاسيك برجر",
    nameEn: "Classic Burger",
    descriptionAr: "برجر كلاسيكي مع خس، طماطم، مخلل وصوص خاص",
    descriptionEn: "Classic burger with lettuce, tomato, pickles, and special sauce",
    basePrice: 28,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 4,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1005,
    nameAr: "دجاج كرسبي",
    nameEn: "Crispy Chicken",
    descriptionAr: "صدر دجاج مقرمش مع الخس والمايونيز والجبنة",
    descriptionEn: "Crispy chicken breast with lettuce, mayonnaise, and cheese",
    basePrice: 25,
    discount: 0,
    categoryId: 102,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1606755962773-d32172e7a202?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1006,
    nameAr: "بوفالو دجاج برجر",
    nameEn: "Buffalo Chicken Burger",
    descriptionAr: "دجاج مقرمش مغمس بصوص البوفالو الحار مع المخلل والمايونيز",
    descriptionEn: "Crispy chicken tossed in spicy buffalo sauce with pickles and mayonnaise",
    basePrice: 27,
    discount: 0,
    categoryId: 102,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1615486171448-4fdcf594d215?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1007,
    nameAr: "ساندويتش فيلي ستيك",
    nameEn: "Philly Steak Sandwich",
    descriptionAr: "شرائح لحم بقري ريب آي مع البصل والمشروم والفلفل والجبنة المذابة",
    descriptionEn: "Ribeye steak slices with onions, mushrooms, peppers and melted cheese",
    basePrice: 30,
    discount: 0,
    categoryId: 103,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1628198539209-77f6bbfd0ec5?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1008,
    nameAr: "ساندويتش فاهيتا دجاج",
    nameEn: "Chicken Fajita Sandwich",
    descriptionAr: "دجاج متبل على الطريقة المكسيكية مع الفلفل الألوان والبصل والجبنة",
    descriptionEn: "Mexican spiced chicken with bell peppers, onions and cheese",
    basePrice: 25,
    discount: 0,
    categoryId: 103,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1626244405389-7008cf585d82?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1009,
    nameAr: "بوكس التوفير",
    nameEn: "Saver Box",
    descriptionAr: "4 برجر كلاسيك، 2 بطاطس حجم عائلي، 1 بيبسي لتر",
    descriptionEn: "4 Classic burgers, 2 family fries, 1L Pepsi",
    basePrice: 110,
    discount: 0,
    categoryId: 104,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1010,
    nameAr: "بطاطا مقلية صينية",
    nameEn: "French Fries",
    descriptionAr: "بطاطا مقرمشة ذهبية",
    descriptionEn: "Golden crispy french fries",
    basePrice: 10,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1011,
    nameAr: "أصابع الموزاريلا",
    nameEn: "Mozzarella Sticks",
    descriptionAr: "أصابع موزاريلا مقرمشة تقدم مع صوص المارينارا (5 قطع)",
    descriptionEn: "Crispy mozzarella sticks served with marinara sauce (5 pieces)",
    basePrice: 15,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1531749668029-2be8c962bda5?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1012,
    nameAr: "أجنحة الدجاج",
    nameEn: "Chicken Wings",
    descriptionAr: "أجنحة دجاج مقلية بصوص البافلو أو الباربكيو (6 قطع)",
    descriptionEn: "Fried chicken wings tossed in buffalo or BBQ sauce (6 pieces)",
    basePrice: 20,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 3,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1565299585323-38d1b7371a58?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1013,
    nameAr: "بيبسي",
    nameEn: "Pepsi",
    descriptionAr: "علبة بيبسي",
    descriptionEn: "Pepsi Can",
    basePrice: 4,
    discount: 0,
    categoryId: 106,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1014,
    nameAr: "سفن أب",
    nameEn: "7up",
    descriptionAr: "علبة سفن أب",
    descriptionEn: "7up Can",
    basePrice: 4,
    discount: 0,
    categoryId: 106,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1015,
    nameAr: "ماء",
    nameEn: "Water",
    descriptionAr: "زجاجة مياه معدنية صغيرة",
    descriptionEn: "Small mineral water bottle",
    basePrice: 3,
    discount: 0,
    categoryId: 106,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 3,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1016,
    nameAr: "تشيز كيك نيويورك",
    nameEn: "New York Cheesecake",
    descriptionAr: "قطعة من التشيز كيك الكلاسيكي بصوص الفراولة",
    descriptionEn: "A slice of classic cheesecake with strawberry sauce",
    basePrice: 20,
    discount: 0,
    categoryId: 107,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 1,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1017,
    nameAr: "مولتن شوكليت كيك",
    nameEn: "Molten Chocolate Cake",
    descriptionAr: "كيك الشوكولاتة الدافئ مع الآيس كريم",
    descriptionEn: "Warm chocolate cake with ice cream",
    basePrice: 22,
    discount: 0,
    categoryId: 107,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 2,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1018,
    nameAr: "أولد سكول برجر",
    nameEn: "Old School Burger",
    descriptionAr: "شريحة لحم كلاسيكية مع إضافات أبتاون الأصلية",
    descriptionEn: "Classic beef patty with original Uptown additions",
    basePrice: 35,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 5,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1019,
    nameAr: "سماش برجر",
    nameEn: "Smash Burger",
    descriptionAr: "شريحتين رقيقتين من اللحم المشوي، جبنة، صوص سماش",
    descriptionEn: "Two thin smashed beef patties, cheese, smash sauce",
    basePrice: 32,
    discount: 0,
    categoryId: 101,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 6,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1020,
    nameAr: "فيليه دجاج برجر",
    nameEn: "Chicken Filet Burger",
    descriptionAr: "فيليه دجاج مشوي مع الخس والطماطم",
    descriptionEn: "Grilled chicken filet with lettuce and tomato",
    basePrice: 28,
    discount: 0,
    categoryId: 102,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 3,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1606755962773-d32172e7a202?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1021,
    nameAr: "ساندويش حبش مدخن",
    nameEn: "Smoked Turkey Sandwich",
    descriptionAr: "شرائح الحبش المدخن مع الجبنة والخس",
    descriptionEn: "Smoked turkey slices with cheese and lettuce",
    basePrice: 20,
    discount: 0,
    categoryId: 103,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 3,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1628198539209-77f6bbfd0ec5?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1022,
    nameAr: "زنجر ساندويتش",
    nameEn: "Zinger Sandwich",
    descriptionAr: "دجاج زنجر حار ومقرمش",
    descriptionEn: "Spicy and crispy Zinger chicken",
    basePrice: 22,
    discount: 0,
    categoryId: 103,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 4,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1626244405389-7008cf585d82?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1023,
    nameAr: "شاورما دجاج بخبز التورتيلا",
    nameEn: "Chicken Shawarma Wrap",
    descriptionAr: "شاورما دجاج الطازجة في خبز التورتيلا والمثومة",
    descriptionEn: "Fresh chicken shawarma in tortilla bread with garlic sauce",
    basePrice: 15,
    discount: 0,
    categoryId: 103,
    branchId: null,
    allBranches: true,
    hasMealOption: true,
    hasDonenessOption: false,
    sortOrder: 5,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1529144415895-6aaf8be872fb?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1024,
    nameAr: "ودجز",
    nameEn: "Wedges",
    descriptionAr: "بطاطس ودجز المتبلة",
    descriptionEn: "Seasoned potato wedges",
    basePrice: 12,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 4,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1025,
    nameAr: "حلقات البصل",
    nameEn: "Onion Rings",
    descriptionAr: "حلقات بصل مقرمشة وذهبية",
    descriptionEn: "Crispy golden onion rings",
    basePrice: 14,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 5,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1639024471283-03518883512d?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1026,
    nameAr: "ناجتس الدجاج",
    nameEn: "Chicken Nuggets",
    descriptionAr: "قطع الناجتس (8 قطع)",
    descriptionEn: "Chicken nuggets (8 pieces)",
    basePrice: 16,
    discount: 0,
    categoryId: 105,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 6,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1027,
    nameAr: "ميرندا",
    nameEn: "Miranda",
    descriptionAr: "ميرندا برتقال باردة",
    descriptionEn: "Cold orange miranda",
    basePrice: 4,
    discount: 0,
    categoryId: 106,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 4,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  },
  {
    id: 1028,
    nameAr: "ميلك شيك فراولة",
    nameEn: "Strawberry Milkshake",
    descriptionAr: "ميلك شيك منعش بنكهة الفراولة",
    descriptionEn: "Refreshing strawberry milkshake",
    basePrice: 18,
    discount: 0,
    categoryId: 106,
    branchId: null,
    allBranches: true,
    hasMealOption: false,
    hasDonenessOption: false,
    sortOrder: 5,
    isActive: true,
    imagePath: "https://images.unsplash.com/photo-1579954115545-a95f9ab7a4ea?q=80&w=800&auto=format&fit=crop",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), sizes: [], types: []
  }
];

export const mockAddonGroups = [
  {
    id: 1,
    nameAr: "إضافات مدفوعة",
    nameEn: "Paid Addons",
    categoryId: 1,
    productId: null,
    groupType: "addons",
    isRequired: false,
    allowMultiple: true,
    sortOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: 1,
        addonGroupId: 1,
        nameAr: "جبنة إضافية",
        nameEn: "Extra Cheese",
        price: 3,
        sortOrder: 1,
        isActive: true
      }
    ]
  },
  {
    id: 2,
    nameAr: "بدون إضافات",
    nameEn: "Without Addons",
    categoryId: 1,
    productId: null,
    groupType: "without",
    isRequired: false,
    allowMultiple: true,
    sortOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: 2,
        addonGroupId: 2,
        nameAr: "بدون بصل",
        nameEn: "Without Onions",
        price: 0,
        sortOrder: 1,
        isActive: true
      },
      {
        id: 3,
        addonGroupId: 2,
        nameAr: "بدون مخلل",
        nameEn: "Without Pickles",
        price: 0,
        sortOrder: 2,
        isActive: true
      }
    ]
  }
];

export const mockSettings = {
  id: 1,
  siteName: "UPTOWN",
  siteNameAr: "أبتاون",
  logoUrl: null,
  currencySymbol: "₪",
  primaryColor: "#c8151d",
  secondaryColor: "#1a1a1a",
  footerText: "By Menuna",
  ogImageUrl: null,
  metaDescriptionAr: "أبتاون - مطعم برجر وساندويتشات فاخرة",
  metaDescriptionEn: "UPTOWN - Premium burgers and sandwiches restaurant",
  tiktokUrl: null,
  instagramUptownUrl: null,
  facebookUptownUrl: null,
  facebookPastaUrl: null,
  instagramPastaUrl: null,
  updatedAt: new Date().toISOString()
};

export const mockBanners = [
  {
    id: 1,
    name: "Banner 1",
    imagePath: "/uploads/mainscreen/3018f9b8daf9db07b400c2f718a469da.webp",
    sortOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
